### PR TITLE
fixed json request reading

### LINKED ISSUE #108: Export feature broken by PR #106
The export feature no longer works since PR #106. It causes a 500 server error due to a java exception. Here is a sample from the error logs in `/opt/tomcat/logs/catalina.out`

```
org.json.JSONException: Expected a ':' after a key at character 7259
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:203)
	at org.json.JSONTokener.nextValue(JSONTokener.java:344)
	at org.json.JSONArray.<init>(JSONArray.java:125)
	at org.json.JSONTokener.nextValue(JSONTokener.java:348)
	at org.json.JSONObject.<init>(JSONObject.java:205)
	at org.json.JSONTokener.nextValue(JSONTokener.java:344)
	at org.json.JSONObject.<init>(JSONObject.java:205)
	at org.json.JSONTokener.nextValue(JSONTokener.java:344)
	at org.json.JSONArray.<init>(JSONArray.java:125)
	at org.json.JSONTokener.nextValue(JSONTokener.java:348)
	at org.json.JSONObject.<init>(JSONObject.java:205)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at CPServlet.getRequestJson(CPServlet.java:60)
	at SequenceExporter.doPost(SequenceExporter.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by Davidster**
Instead of reading the request body of incoming POST's via BufferedReader, I simply used the apache commons io library to generate the string before it gets parsed as JSON. This resolves #108.

### CODE REVIEW

File: src/main/java/CPServlet.java [hunk 1]
```diff
@@ -39,28 +40,16 @@ public void init(ServletConfig config) throws ServletException {
...
-            while ((line = reader.readLine()) != null) {
-                jb.append(line);
-            }
-            reader.close();
-        } catch (Exception e) {
-            e.printStackTrace();
-            throw new IOException("Error reading from request string");
-        }
+	String requestString = IOUtils.toString(request.getReader());
         try {
```
Comment (stumash) [inline src/main/java/CPServlet.java]: ugh what java
