### PR TITLE
fixes to deploy.sh and add deployScraper.sh

### LINKED ISSUE #51: Deploy success message broken
If there are errors in the building of the frontend components (babel, browserify, etc), the deploy script claims to have succeeded and proceeds to transfer courseplanner.war to the VM. This should not be the case

### LINKED ISSUE #60: Deploy prod version of react with prod version of project and vice versa
Instead of using `x` as a param for `deploy.sh`, simply build the frontend with a development version of react for our personal war files (`courseplanner{d,s,p,j,m}`) and with a production version of react when were pushing to prod (`courseplanner`).

### PR DESCRIPTION
**Pull request by stumash**
### new usage of `deploy.sh`:
1st arg (required): either
* '`prod`' to deploy to production .war file using production version of React, or
* '`<devname>`' (where `<devname>` should be replaced with the dev's name) to deploy to the dev's .war file using the development version of React

2nd arg (optional):
* '`--verbose`' to see all `npm` and `maven` output.  Omit this arg to silence both `npm` and `maven`

So, an example usage would be `./deploy.sh stu --verbose`.  Another example: `./deploy.sh prod`

### add `deployScraper.sh`
I have added the file `deployScraper.sh` which can be used to copy over your current version of the `webscraping` directory to one the used on the server, which it keeps at `/opt/cp-webscraping`. 

`deployScraper.sh` contains only one line of code, a call to `rsync`.

this PR resolves #60 and resolves #51.

### CODE REVIEW

File: deploy.sh [hunk 1]
```diff
@@ -2,53 +2,87 @@
...
+echo ""
 
-if ! $projectBuildSuccessful
+# compile backend sources and package frontend assets
+mvnCommand="mvn clean install"
+echo "building backend... (maven)"
+if eval $mvnCommand $verbose
 then
-    echo "Project build failed" 1>&2
+    echo "backend build succssful. Transferring war file to VM"
```
Comment (Davidster) [inline deploy.sh]: remove " Transferring war file to VM"
